"""Beckhoff TwinCAT 3 backend.

Emits native TwinCAT PLC project items (add to a TwinCAT PLC project or
drive via the Automation Interface later - engine phase):

    GVL_<Project>.TcGVL   global variable list (IR global tags)
    <Program>.TcPOU       one PROGRAM POU per IR program, ST body

POU Ids are deterministic (uuid5 of project+pou) so re-generation diffs
cleanly under version control.
"""

from __future__ import annotations

import uuid
from pathlib import Path
from xml.sax.saxutils import quoteattr

from ladder.backends import common
from ladder.backends.base import Backend, register
from ladder.backends.dialects import Iec61131Dialect
from ladder.ir.lower import LoweredProgram
from ladder.ir.model import Project

_NS = uuid.UUID("6f9619ff-8b86-4011-b42d-00cf4fc964ff")


def _guid(*parts: str) -> str:
    return "{" + str(uuid.uuid5(_NS, "/".join(("ladder",) + parts))) + "}"


def _cdata(text: str) -> str:
    return "<![CDATA[" + text.replace("]]>", "]]]]><![CDATA[>") + "]]>"


@register
class BeckhoffBackend(Backend):
    name = "beckhoff"
    description = "Beckhoff TwinCAT 3 - TcPOU programs + TcGVL globals"
    target = "TwinCAT 3.1 (XAE)"
    _addresses: dict[str, str] = {}

    def emit(self, project: Project, lowered: dict[str, LoweredProgram],
             outdir: Path, iomap=None) -> list[Path]:
        self._addresses = ({name: b.address for name, b in
                            iomap.section("beckhoff").items() if b.address}
                           if iomap is not None else {})
        d = Iec61131Dialect()
        root = outdir / "beckhoff"
        root.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        for t in project.types:
            dut = root / f"{t.name}.TcDUT"
            dut.write_text(self._render_dut(project, t), encoding="utf-8")
            written.append(dut)

        if project.tags:
            gvl = root / f"GVL_{project.name}.TcGVL"
            gvl.write_text(self._render_gvl(project), encoding="utf-8")
            written.append(gvl)

        for name, lp in lowered.items():
            path = root / f"{name}.TcPOU"
            path.write_text(self._render_pou(project, name, lp, d), encoding="utf-8")
            written.append(path)
        return written

    def _render_dut(self, project: Project, struct) -> str:
        decl = common.iec_struct_lines(struct)
        return "\n".join([
            '<?xml version="1.0" encoding="utf-8"?>',
            '<TcPlcObject Version="1.1.0.1">',
            f"  <DUT Name={quoteattr(struct.name)} Id=\"{_guid(project.name, struct.name)}\">",
            f"    <Declaration>{_cdata(chr(10).join(decl))}</Declaration>",
            "  </DUT>",
            "</TcPlcObject>",
            "",
        ])

    def _render_gvl(self, project: Project) -> str:
        decl = [f"// generated by LADDER for {project.name} - do not edit by hand",
                "VAR_GLOBAL"]
        for t in project.tags:
            line = common.iec_var_line(t)
            at = self._addresses.get(t.name)
            if at:  # TwinCAT located variable: name AT %IX0.0 : BOOL;
                line = line.replace(f"{t.name} :", f"{t.name} AT {at} :", 1)
            decl.append(line)
        decl.append("END_VAR")
        name = f"GVL_{project.name}"
        return "\n".join([
            '<?xml version="1.0" encoding="utf-8"?>',
            '<TcPlcObject Version="1.1.0.1">',
            f"  <GVL Name={quoteattr(name)} Id=\"{_guid(project.name, name)}\">",
            f"    <Declaration>{_cdata(chr(10).join(decl))}</Declaration>",
            "  </GVL>",
            "</TcPlcObject>",
            "",
        ])

    def _render_pou(self, project: Project, name: str, lp: LoweredProgram,
                    d: Iec61131Dialect) -> str:
        decl = [f"PROGRAM {name}"]
        if lp.program.description:
            decl.insert(0, f"// {lp.program.description}")
        locals_ = common.local_declarations(lp, d)
        if locals_:
            decl.append("VAR")
            decl.extend(locals_)
            decl.append("END_VAR")
        else:
            decl += ["VAR", "END_VAR"]
        return "\n".join([
            '<?xml version="1.0" encoding="utf-8"?>',
            '<TcPlcObject Version="1.1.0.1">',
            f"  <POU Name={quoteattr(name)} Id=\"{_guid(project.name, name)}\" SpecialFunc=\"None\">",
            f"    <Declaration>{_cdata(chr(10).join(decl))}</Declaration>",
            "    <Implementation>",
            f"      <ST>{_cdata(d.body(lp))}</ST>",
            "    </Implementation>",
            "  </POU>",
            "</TcPlcObject>",
            "",
        ])
