"""EPICS interface backend: the control-system-facing artifacts.

Labs that run EPICS want the PLC's operator-facing signals as process
variables the moment the PLC exists (pytmc proved the demand on the
TwinCAT side). This backend emits, from the same IR + iomap:

  <Name>.db          one record per directional tag - bi/bo for BOOL,
                     ai/ao for analog - with alarm severities wired
                     from the IR's alarm elements (MINOR/MAJOR per the
                     element's `severity`), macros for the site prefix
                     and link so any device support (OPC UA, s7plc,
                     Modbus) can be substituted at load time
  <Name>-alarms.csv  the alarm handler / archiver seed list: PV, tag,
                     severity, message, ack behavior

Deliberately transport-agnostic: INP/OUT links are `$(LINK=...)` macros
because the s7plc-vs-opcua-vs-modbus choice is a facility decision, not
a design property. Load with:

    dbLoadRecords("Plant.db", "P=SR01:,LINK=@opcua ...")
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from ladder.backends.base import Backend, register
from ladder.ir.lower import LoweredProgram
from ladder.ir.model import AlarmEl, AlarmGroupEl, Project

_SEVERITY = {"info": "MINOR", "warning": "MINOR", "alarm": "MAJOR",
             "critical": "MAJOR"}


def _pv(name: str) -> str:
    """Tag name -> PV suffix: EPICS convention, colon-separated caps."""
    return name.replace(".", ":").replace("_", "").upper()


def _alarm_map(project: Project) -> dict[str, tuple[str, str]]:
    """output tag -> (severity, message) from alarm/alarm_group elements."""
    out: dict[str, tuple[str, str]] = {}
    for prog in project.programs:
        for el in prog.logic:
            if isinstance(el, AlarmEl) and el.output:
                sev = _SEVERITY.get(getattr(el, "severity", "alarm"), "MAJOR")
                out[el.output] = (sev, el.description or el.id)
            elif isinstance(el, AlarmGroupEl):
                for m in el.alarms:
                    if m.output:
                        out[m.output] = ("MAJOR", m.name)
                if el.active:
                    out[el.active] = ("MAJOR", f"{el.id} group active")
    return out


@register
class EpicsBackend(Backend):
    name = "epics"
    description = "EPICS interface: .db records + alarm list from IR + iomap"
    target = "EPICS 7 (transport-agnostic links via macros)"

    def emit(self, project: Project, lowered: dict[str, LoweredProgram],
             outdir: Path, iomap: Optional["IoMap"] = None) -> list[Path]:
        d = outdir / "epics"
        d.mkdir(parents=True, exist_ok=True)
        alarms = _alarm_map(project)
        bindings = {}
        if iomap is not None:
            bindings = {k: (v.address or v.alias)
                        for k, v in iomap.section("epics").items()}

        db_lines = [f"# {project.name} - generated by LADDER (epics backend)",
                    "# macros: P = PV prefix, LINK = device-support link", ""]
        alarm_rows = ["pv,tag,severity,message"]
        for t in project.tags:
            if not t.direction or t.array is not None:
                continue
            base = t.type.upper()
            if base == "BOOL":
                rtyp = "bi" if t.direction == "input" else "bo"
            elif base in ("INT", "DINT", "REAL", "LREAL", "WORD", "DWORD"):
                rtyp = "ai" if t.direction == "input" else "ao"
            else:
                continue  # UDT/STRING instances: not direct PVs
            pv = _pv(t.name)
            link_field = "INP" if rtyp in ("bi", "ai") else "OUT"
            link = bindings.get(t.name, f"$(LINK=){t.name}")
            db_lines.append(f'record({rtyp}, "$(P){pv}") {{')
            if t.comment:
                db_lines.append(f'    field(DESC, "{t.comment[:40]}")')
            db_lines.append(f'    field({link_field}, "{link}")')
            if rtyp in ("bi", "bo"):
                db_lines.append('    field(ZNAM, "FAULT/OFF")')
                db_lines.append('    field(ONAM, "OK/ON")')
            if t.name in alarms:
                sev, msg = alarms[t.name]
                # alarm outputs: 1 = alarm active -> severity on state one
                db_lines.append(f'    field(OSV, "{sev}")')
                alarm_rows.append(f'$(P){pv},{t.name},{sev},"{msg}"')
            elif rtyp == "bi" and t.name.endswith("_ok"):
                # fail-safe sense: 0 (unhealthy) is the alarm state
                db_lines.append('    field(ZSV, "MAJOR")')
            db_lines.append("    field(SCAN, \"I/O Intr\")")
            db_lines.append("}")
            db_lines.append("")

        db = d / f"{project.name}.db"
        db.write_text("\n".join(db_lines), encoding="ascii")
        csv = d / f"{project.name}-alarms.csv"
        csv.write_text("\n".join(alarm_rows) + "\n", encoding="ascii")
        return [db, csv]
