"""Plain IEC 61131-3 Structured Text backend.

Emits one standards-conformant .st source file: PROGRAM POUs (with
VAR_EXTERNAL declarations for the globals they touch) plus a
CONFIGURATION/RESOURCE binding every program to a task.

Two jobs:
  1. Vendor-free verification - the file compiles with open tools
     (matiec's iec2c, IronPLC), so CI can check every generated program
     without any vendor install.
  2. Human-readable neutral output - reviewers see exactly what the IR
     means without opening a vendor tool.

Strict-IEC notes: comments are (* *) only (matiec is edition-2 strict),
and globals referenced by a POU are declared VAR_EXTERNAL as the standard
requires.
"""

from __future__ import annotations

from pathlib import Path

from ladder.backends.base import Backend, register
from ladder.backends.common import fmt_initial, iec_type_text
from ladder.backends.dialects import Iec61131Dialect, RenderContext
from ladder.ir import expr as X
from ladder.ir.lower import (
    LoweredProgram,
    SAssign,
    SCase,
    SIf,
    SRaw,
    STimerCall,
    Stmt,
)
from ladder.ir.model import Project

_CYCLE = "T#20ms"  # default task interval for cyclic programs


def _safe_comment(text: str) -> str:
    return text.replace("*)", "* )")


class StrictIecDialect(Iec61131Dialect):
    """Edition-2-strict ST: (* *) comments only (matiec rejects //)."""

    name = "iec-strict"

    def comment(self, text: str) -> list[str]:
        return [f"(* {_safe_comment(text)} *)"]


def _stmt_refs(s: Stmt) -> list[X.Ref]:
    """Every Ref a statement touches (SRaw is opaque - callers handle it)."""
    out: list[X.Ref] = []
    if isinstance(s, SAssign):
        out.append(s.target)
        out.extend(X.refs(s.value))
    elif isinstance(s, SIf):
        out.extend(X.refs(s.cond))
        for cond, body in s.elifs:
            out.extend(X.refs(cond))
            for b in body:
                out.extend(_stmt_refs(b))
        for b in (*s.then, *s.orelse):
            out.extend(_stmt_refs(b))
    elif isinstance(s, SCase):
        out.append(s.selector)
        for _, _, body in s.cases:
            for b in body:
                out.extend(_stmt_refs(b))
    elif isinstance(s, STimerCall):
        out.extend(X.refs(s.input))
    return out


def external_globals(project: Project, lp: LoweredProgram) -> list:
    """Global tags this program references, in project declaration order."""
    local = {t.name for t in lp.program.variables}
    local.update(v.name for v in lp.synth)
    roots: set[str] = set()
    for s in lp.statements:
        for ref in _stmt_refs(s):
            if ref.root not in local:
                roots.add(ref.root)
        if isinstance(s, SRaw):
            # opaque: conservatively require every global (correct, just wide)
            roots.update(t.name for t in project.tags)
    return [t for t in project.tags if t.name in roots]


@register
class IecBackend(Backend):
    name = "iec"
    description = "Plain IEC 61131-3 ST - vendor-free verification via matiec/IronPLC"
    target = "IEC 61131-3 ed.2 (open toolchains)"
    _addresses: dict[str, str] = {}

    def emit(self, project: Project, lowered: dict[str, LoweredProgram],
             outdir: Path, iomap=None) -> list[Path]:
        self._addresses = ({name: b.address for name, b in
                            iomap.section("iec").items() if b.address}
                           if iomap is not None else {})
        root = outdir / "iec"
        root.mkdir(parents=True, exist_ok=True)
        path = root / f"{project.name}.st"
        path.write_text(self._render(project, lowered), encoding="ascii")
        return [path]

    def _render(self, project: Project, lowered: dict[str, LoweredProgram]) -> str:
        d = StrictIecDialect()
        out: list[str] = [f"(* {_safe_comment(project.name)} - generated by LADDER *)"]
        if project.description:
            out.append(f"(* {_safe_comment(project.description)} *)")
        out.append("")

        if project.types:
            out.append("TYPE")
            for t in project.types:
                out.append(f"    {t.name} :")
                out.append("        STRUCT")
                for m in t.members:
                    init = fmt_initial(m.initial, m.type)
                    line = f"            {m.name} : {m.type}"  # scalars pre-normalized
                    if init is not None:
                        line += f" := {init}"
                    out.append(line + ";")
                out.append("        END_STRUCT;")
            out.append("END_TYPE")
            out.append("")

        for name, lp in lowered.items():
            out.extend(self._pou(project, name, lp, d))
            out.append("")

        out.extend(self._configuration(project, lowered))
        return "\n".join(out) + "\n"

    def _pou(self, project: Project, name: str, lp: LoweredProgram,
             d: StrictIecDialect) -> list[str]:
        # render the body first: the IL renderer may add BOOL temporaries
        extra_bools: list[str] = []
        note = None
        if lp.program.language == "il":
            from ladder.backends.il import IlRenderer

            renderer = IlRenderer()
            body = renderer.body(lp)
            extra_bools = renderer.extra_bools
        elif lp.program.language == "sfc":
            body = self._sfc_body(lp, d)
        else:
            body = d.body(lp)
            if lp.program.language in ("ladder", "fbd"):
                note = (f"language '{lp.program.language}' is graphic-only; "
                        "rendered as equivalent ST (see the plcopen backend "
                        "for the graphic body)")

        out = [f"PROGRAM {name}"]
        if note:
            out.append(f"(* {note} *)")
        ext = external_globals(project, lp)
        if ext:
            out.append("VAR_EXTERNAL")
            out.extend(f"    {t.name} : {iec_type_text(t)};" for t in ext)
            out.append("END_VAR")
        locals_ = []
        for t in lp.program.variables:
            init = fmt_initial(t.initial, t.type) if t.array is None else None
            locals_.append(f"    {t.name} : {iec_type_text(t)}"
                           + (f" := {init}" if init is not None else "") + ";")
        from ladder.backends.common import synth_type

        for v in lp.synth:
            locals_.append(f"    {v.name} : {synth_type(v, d)};"
                           + (f"  (* {_safe_comment(v.comment)} *)" if v.comment else ""))
        for extra in extra_bools:
            locals_.append(f"    {extra} : BOOL;  (* IL timer-input temporary *)")
        if locals_:
            out.append("VAR")
            out.extend(locals_)
            out.append("END_VAR")
        out.append("")
        out.extend("    " + line if line else "" for line in body.splitlines())
        out.append("END_PROGRAM")
        return out

    def _sfc_body(self, lp: LoweredProgram, d: StrictIecDialect) -> str:
        """Textual SFC (IEC 61131-3 B.1.6): steps with action associations,
        named ACTIONs, prioritized TRANSITIONs. matiec compiles this, so CI
        proves SFC output like every other language."""
        from ladder.backends.dialects import RenderContext
        from ladder.ir.lower import state_codes
        from ladder.ir.model import StateMachineEl, compile_cond

        el = next(e for e in lp.program.logic if isinstance(e, StateMachineEl))
        codes = state_codes(el)
        ctx = RenderContext.for_program(lp)
        out: list[str] = []
        for st in el.states:
            kw = "INITIAL_STEP" if st.name == el.initial else "STEP"
            out.append(f"{kw} {st.name}:")
            out.append(f"    {st.name}_act(N);")
            out.append("END_STEP")
        out.append("")
        for st in el.states:
            for k, tr in enumerate(st.transitions):
                cond = d.expr(compile_cond(tr.when), ctx)
                out.append(f"TRANSITION (PRIORITY := {k + 1}) "
                           f"FROM {st.name} TO {tr.goto}")
                out.append(f"    := {cond};")
                out.append("END_TRANSITION")
        out.append("")
        for st in el.states:
            out.append(f"ACTION {st.name}_act:")
            # keep the state tag truthful for anything else reading it
            out.append(f"    {d.fmt_ref(X.Ref(tuple(el.state_tag.split('.'))), ctx)}"
                       f" := {codes[st.name]};")
            for act in st.do:
                target = d.fmt_ref(X.Ref(tuple(act.target.split('.'))), ctx)
                out.append(f"    {target} := {d.expr(compile_cond(act.value), ctx)};")
            out.append("END_ACTION")
        return "\n".join(out) + "\n"

    def _configuration(self, project: Project,
                       lowered: dict[str, LoweredProgram]) -> list[str]:
        out = ["CONFIGURATION Config", "  RESOURCE Res ON PLC"]
        if project.tags:
            out.append("    VAR_GLOBAL")
            for t in project.tags:
                init = fmt_initial(t.initial, t.type) if t.array is None else None
                at = self._addresses.get(t.name)
                located = f" AT {at}" if at else ""  # 61131 located variable
                out.append(f"        {t.name}{located} : {iec_type_text(t)}"
                           + (f" := {init}" if init is not None else "") + ";")
            out.append("    END_VAR")
        cyclic = [n for n, lp in lowered.items() if lp.program.execution == "cyclic"]
        if cyclic:
            out.append(f"    TASK MainTask(INTERVAL := {_CYCLE}, PRIORITY := 1);")
        for n, lp in lowered.items():
            if lp.program.execution == "periodic":
                out.append(f"    TASK Task_{n}(INTERVAL := {lp.program.interval}, "
                           f"PRIORITY := 1);")
        for n, lp in lowered.items():
            task = "MainTask" if lp.program.execution == "cyclic" else f"Task_{n}"
            out.append(f"    PROGRAM inst_{n} WITH {task} : {n};")
        out.extend(["  END_RESOURCE", "END_CONFIGURATION"])
        return out
