"""Plain IEC 61131-3 Structured Text backend.

Emits one standards-conformant .st source file: PROGRAM POUs (with
VAR_EXTERNAL declarations for the globals they touch) plus a
CONFIGURATION/RESOURCE binding every program to a task.

Two jobs:
  1. Vendor-free verification - the file compiles with open tools
     (matiec's iec2c, IronPLC), so CI can check every generated program
     without any vendor install.
  2. Human-readable neutral output - reviewers see exactly what the IR
     means without opening a vendor tool.

Strict-IEC notes: comments are (* *) only (matiec is edition-2 strict),
and globals referenced by a POU are declared VAR_EXTERNAL as the standard
requires.
"""

from __future__ import annotations

from pathlib import Path

from ladder.backends.base import Backend, register
from ladder.backends.common import fmt_initial
from ladder.backends.dialects import Iec61131Dialect, RenderContext
from ladder.ir import expr as X
from ladder.ir.lower import (
    LoweredProgram,
    SAssign,
    SCase,
    SIf,
    SRaw,
    STimerCall,
    Stmt,
)
from ladder.ir.model import Project

_CYCLE = "T#20ms"  # default task interval for cyclic programs


def _safe_comment(text: str) -> str:
    return text.replace("*)", "* )")


class StrictIecDialect(Iec61131Dialect):
    """Edition-2-strict ST: (* *) comments only (matiec rejects //)."""

    name = "iec-strict"

    def comment(self, text: str) -> list[str]:
        return [f"(* {_safe_comment(text)} *)"]


def _stmt_refs(s: Stmt) -> list[X.Ref]:
    """Every Ref a statement touches (SRaw is opaque - callers handle it)."""
    out: list[X.Ref] = []
    if isinstance(s, SAssign):
        out.append(s.target)
        out.extend(X.refs(s.value))
    elif isinstance(s, SIf):
        out.extend(X.refs(s.cond))
        for cond, body in s.elifs:
            out.extend(X.refs(cond))
            for b in body:
                out.extend(_stmt_refs(b))
        for b in (*s.then, *s.orelse):
            out.extend(_stmt_refs(b))
    elif isinstance(s, SCase):
        out.append(s.selector)
        for _, _, body in s.cases:
            for b in body:
                out.extend(_stmt_refs(b))
    elif isinstance(s, STimerCall):
        out.extend(X.refs(s.input))
    return out


def external_globals(project: Project, lp: LoweredProgram) -> list:
    """Global tags this program references, in project declaration order."""
    local = {t.name for t in lp.program.variables}
    local.update(v.name for v in lp.synth)
    roots: set[str] = set()
    for s in lp.statements:
        for ref in _stmt_refs(s):
            if ref.root not in local:
                roots.add(ref.root)
        if isinstance(s, SRaw):
            # opaque: conservatively require every global (correct, just wide)
            roots.update(t.name for t in project.tags)
    return [t for t in project.tags if t.name in roots]


@register
class IecBackend(Backend):
    name = "iec"
    description = "Plain IEC 61131-3 ST - vendor-free verification via matiec/IronPLC"
    target = "IEC 61131-3 ed.2 (open toolchains)"

    def emit(self, project: Project, lowered: dict[str, LoweredProgram],
             outdir: Path) -> list[Path]:
        root = outdir / "iec"
        root.mkdir(parents=True, exist_ok=True)
        path = root / f"{project.name}.st"
        path.write_text(self._render(project, lowered), encoding="ascii")
        return [path]

    def _render(self, project: Project, lowered: dict[str, LoweredProgram]) -> str:
        d = StrictIecDialect()
        out: list[str] = [f"(* {_safe_comment(project.name)} - generated by LADDER *)"]
        if project.description:
            out.append(f"(* {_safe_comment(project.description)} *)")
        out.append("")

        for name, lp in lowered.items():
            out.extend(self._pou(project, name, lp, d))
            out.append("")

        out.extend(self._configuration(project, lowered))
        return "\n".join(out) + "\n"

    def _pou(self, project: Project, name: str, lp: LoweredProgram,
             d: StrictIecDialect) -> list[str]:
        out = [f"PROGRAM {name}"]
        ext = external_globals(project, lp)
        if ext:
            out.append("VAR_EXTERNAL")
            out.extend(f"    {t.name} : {t.type.upper()};" for t in ext)
            out.append("END_VAR")
        locals_ = []
        for t in lp.program.variables:
            init = fmt_initial(t.initial, t.type)
            locals_.append(f"    {t.name} : {t.type.upper()}"
                           + (f" := {init}" if init is not None else "") + ";")
        for v in lp.synth:
            type_ = d.timer_decl_type(v) if v.kind == "timer" else "BOOL"
            locals_.append(f"    {v.name} : {type_};"
                           + (f"  (* {_safe_comment(v.comment)} *)" if v.comment else ""))
        if locals_:
            out.append("VAR")
            out.extend(locals_)
            out.append("END_VAR")
        out.append("")
        out.extend("    " + line if line else "" for line in d.body(lp).splitlines())
        out.append("END_PROGRAM")
        return out

    def _configuration(self, project: Project,
                       lowered: dict[str, LoweredProgram]) -> list[str]:
        out = ["CONFIGURATION Config", "  RESOURCE Res ON PLC"]
        if project.tags:
            out.append("    VAR_GLOBAL")
            for t in project.tags:
                init = fmt_initial(t.initial, t.type)
                out.append(f"        {t.name} : {t.type.upper()}"
                           + (f" := {init}" if init is not None else "") + ";")
            out.append("    END_VAR")
        cyclic = [n for n, lp in lowered.items() if lp.program.execution == "cyclic"]
        if cyclic:
            out.append(f"    TASK MainTask(INTERVAL := {_CYCLE}, PRIORITY := 1);")
        for n, lp in lowered.items():
            if lp.program.execution == "periodic":
                out.append(f"    TASK Task_{n}(INTERVAL := {lp.program.interval}, "
                           f"PRIORITY := 1);")
        for n, lp in lowered.items():
            task = "MainTask" if lp.program.execution == "cyclic" else f"Task_{n}"
            out.append(f"    PROGRAM inst_{n} WITH {task} : {n};")
        out.extend(["  END_RESOURCE", "END_CONFIGURATION"])
        return out
