"""Siemens TIA Portal backend (target: V21, S7-1500, Openness).

Emits per project:
    <Program>.scl   one SCL FUNCTION_BLOCK per IR program
    PlcTags.csv     global tag table (Name,DataType,Address,Comment)
    build.ps1       imports everything into TIA via the validated
                    TiaOpenness PowerShell module (E:/TIA_Portal/TIA_API)

The heavy lifting inside the Portal (sessions, tag tables, SCL import,
compile) is delegated to TiaOpenness - LADDER only generates artifacts.
OB wiring / instance DBs / project structure will follow the reverse-
engineered reference project (engine phase).

vendor hints (project.vendor.siemens):
    tia_api_path:  path to the TIA_API repo (default E:/TIA_Portal/TIA_API)
    tia_version:   Openness version for Connect-TiaPortal (default 21.0)
    fb_prefix:     prefix for generated FB names (default 'FB_')
    cpu:           exact CPU TypeIdentifier ('OrderNumber:6ES7 ...') for the
                   scratch build; otherwise build.ps1 tries a candidate list
"""

from __future__ import annotations

from pathlib import Path

from ladder.backends import common
from ladder.backends.base import Backend, BackendError, register
from ladder.backends.dialects import SiemensSclDialect
from ladder.ir.lower import LoweredProgram
from ladder.ir.model import Project, Tag

# Neutral type -> TIA tag-table type casing (PLC-tag-capable types only)
_TIA_TYPES = {"BOOL": "Bool", "INT": "Int", "DINT": "DInt", "REAL": "Real",
              "TIME": "Time", "WORD": "Word", "DWORD": "DWord"}


class _AddrAlloc:
    """Deterministic %I/%Q/%M address allocation for tags without an address.

    Scratch/compile addresses only - real IO mapping is engine-phase (M2).
    BOOLs pack into bits; 16/32-bit types are word/dword aligned.
    """

    _SIZES = {"INT": 2, "WORD": 2, "DINT": 4, "DWORD": 4, "REAL": 4, "TIME": 4}
    _AREA = {"input": "I", "output": "Q", "memory": "M"}

    def __init__(self) -> None:
        self._state = {a: {"byte": 0, "bit": 0} for a in "IQM"}

    def alloc(self, tag: Tag) -> str:
        t = tag.type.upper()
        area = self._AREA[tag.direction]
        st = self._state[area]
        if t == "BOOL":
            addr = f"%{area}{st['byte']}.{st['bit']}"
            st["bit"] += 1
            if st["bit"] == 8:
                st["bit"], st["byte"] = 0, st["byte"] + 1
            return addr
        if t not in self._SIZES:
            raise BackendError(
                f"siemens: tag {tag.name!r} ({tag.type}) cannot be a PLC tag; "
                "give it an explicit address or wait for DB support (IR v0.2)")
        size = self._SIZES[t]
        if st["bit"]:
            st["bit"], st["byte"] = 0, st["byte"] + 1
        if st["byte"] % size:
            st["byte"] += size - (st["byte"] % size)
        width = "W" if size == 2 else "D"
        addr = f"%{area}{width}{st['byte']}"
        st["byte"] += size
        return addr


@register
class SiemensBackend(Backend):
    name = "siemens"
    description = "Siemens TIA Portal V21 - SCL FBs + tag CSV + TiaOpenness build script"
    target = "TIA Portal V21 (Openness)"

    def emit(self, project: Project, lowered: dict[str, LoweredProgram],
             outdir: Path) -> list[Path]:
        hints = self.hints(project)
        fb_prefix = hints.get("fb_prefix", "FB_")
        d = SiemensSclDialect()
        root = outdir / "siemens"
        root.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        for name, lp in lowered.items():
            path = root / f"{fb_prefix}{name}.scl"
            path.write_text(self._render_fb(fb_prefix, lp, d), encoding="utf-8")
            written.append(path)

        tags_csv = root / "PlcTags.csv"
        tags_csv.write_text(self._render_tags_csv(project), encoding="utf-8")
        written.append(tags_csv)

        build = root / "build.ps1"
        build.write_text(self._render_build_ps1(project, lowered, hints, fb_prefix),
                         encoding="ascii")
        written.append(build)
        return written

    # ------------------------------------------------------------------ SCL

    def _render_fb(self, fb_prefix: str, lp: LoweredProgram,
                   d: SiemensSclDialect) -> str:
        prog = lp.program
        out = [f'FUNCTION_BLOCK "{fb_prefix}{prog.name}"']
        out.append("{ S7_Optimized_Access := 'TRUE' }")
        out.append("VERSION : 0.1")
        if prog.description:
            out.append(f"// {prog.description}")
        out.append("// generated by LADDER - do not edit by hand")
        decls = common.local_declarations(lp, d)
        if decls:
            out.append("VAR")
            out.extend(decls)
            out.append("END_VAR")
        out.append("")
        out.append("BEGIN")
        body = d.body(lp)
        out.extend("    " + line if line else "" for line in body.splitlines())
        out.append("END_FUNCTION_BLOCK")
        return "\n".join(out) + "\n"

    # ------------------------------------------------------------------ tags

    def _render_tags_csv(self, project: Project) -> str:
        alloc = _AddrAlloc()
        lines = ["Name,DataType,Address,Comment"]
        for t in project.tags:
            dtype = _TIA_TYPES.get(t.type.upper())
            if dtype is None:
                raise BackendError(
                    f"siemens: {t.type} tag {t.name!r} cannot be a PLC tag; "
                    "DB support arrives with IR v0.2")
            address = t.address or alloc.alloc(t)
            comment = (t.comment or "").replace(",", ";")
            lines.append(f"{t.name},{dtype},{address},{comment}")
        return "\n".join(lines) + "\n"

    # ----------------------------------------------------------------- build

    _BUILD_TEMPLATE = r"""# build.ps1 - build LADDER-generated artifacts in a scratch TIA Portal project
# Generated by LADDER for project '__PROJECT__'. Windows PowerShell 5.1 only.
# Requires the TiaOpenness module: __API__
# Starts its OWN headless portal instance - never touches a human's live session.

param(
    [string]$TiaApiPath  = '__API__',
    [string]$Version     = '__VERSION__',
    [string]$ProjectName = '__PROJECT__',
    [string]$WorkDir     = "$env:TEMP\LADDER_Scratch",
    [string]$Cpu         = '__CPU__',   # exact TypeIdentifier wins over candidates
    [switch]$KeepOpen                    # leave the portal running for inspection
)

$ErrorActionPreference = 'Stop'
$log = Join-Path $PSScriptRoot 'build.log'
Start-Transcript -Path $log -Force | Out-Null
$exit = 1
try {
    Import-Module (Join-Path $TiaApiPath 'src/TiaOpenness/TiaOpenness.psd1') -Force

    Write-Host "Starting headless TIA Portal V$Version ..."
    Connect-TiaPortal -New -WithUserInterface:$false -Version $Version | Out-Null

    $projDir = Join-Path $WorkDir $ProjectName
    if (Test-Path $projDir) { Remove-Item $projDir -Recurse -Force }
    New-TiaProject -Name $ProjectName -Path $WorkDir | Out-Null
    Write-Host "Created scratch project $projDir"

    # CPU: explicit -Cpu first, then candidates until the catalog accepts one.
    $candidates = @()
    if ($Cpu) { $candidates += $Cpu }
    $candidates += @(
        'OrderNumber:6ES7 512-1SK01-0AB0/V2.9'   # CPU 1512SP F-1 PN (in this machine's V21 catalog)
        'OrderNumber:6ES7 511-1AK02-0AB0/V2.9'   # S7-1511-1 PN (standard)
        'OrderNumber:6ES7 513-1AL02-0AB0/V2.9'   # S7-1513-1 PN
        'OrderNumber:6ES7 515-2AM02-0AB0/V2.9'   # S7-1515-2 PN
        'OrderNumber:6ES7 511-1FK02-0AB0/V2.9'   # S7-1511F-1 PN
    )
    $added = $null
    foreach ($mlfb in $candidates) {
        try {
            New-TiaDevice -TypeIdentifier $mlfb -Name 'PLC_1' | Out-Null
            $added = $mlfb; Write-Host "Added CPU: $mlfb"; break
        } catch { Write-Host "  catalog rejected $mlfb" }
    }
    if (-not $added) { throw 'No candidate CPU accepted by this catalog; pass -Cpu with the exact MLFB.' }

    $sw = (Get-TiaPlc | Select-Object -First 1).PlcSoftware

    Write-Host 'Creating PLC tags ...'
    Import-Csv (Join-Path $PSScriptRoot 'PlcTags.csv') | ForEach-Object {
        $p = @{ Plc = $sw; TagTable = 'LADDER'; Name = $_.Name
                DataType = $_.DataType; Address = $_.Address }
        if ($_.Comment) { $p.Comment = $_.Comment }
        New-TiaTag @p | Out-Null
    }

    Write-Host 'Importing SCL blocks ...'
    foreach ($f in @(__SCL_FILES__)) {
        Import-TiaScl -Plc $sw -Path (Join-Path $PSScriptRoot $f) | Out-Null
        Write-Host "  imported $f"
    }

    Write-Host 'Compiling ...'
    $c = Invoke-TiaCompile -Plc $sw
    Write-Host ("Compile State={0} Errors={1} Warnings={2}" -f $c.State, $c.Errors, $c.Warnings)
    $c.Messages | ForEach-Object { Write-Host "  $_" }

    Save-TiaProject
    if ($c.Errors -eq 0) { $exit = 0; Write-Host 'BUILD PASSED (0 errors)' }
    else { Write-Host 'BUILD FAILED (compile errors above)' }
} catch {
    Write-Host "BUILD FAILED: $($_.Exception.Message)"
} finally {
    if (-not $KeepOpen) { try { Disconnect-TiaPortal -Close } catch {} }
    Stop-Transcript | Out-Null
}
exit $exit
"""

    def _render_build_ps1(self, project: Project, lowered: dict[str, LoweredProgram],
                          hints: dict, fb_prefix: str) -> str:
        scl_files = ", ".join(f"'{fb_prefix}{n}.scl'" for n in lowered)
        # ASCII only: PS 5.1 reads BOM-less files as ANSI (TIA_API convention)
        return (self._BUILD_TEMPLATE
                .replace("__API__", str(hints.get("tia_api_path", "E:/TIA_Portal/TIA_API")))
                .replace("__VERSION__", str(hints.get("tia_version", "21.0")))
                .replace("__PROJECT__", project.name)
                .replace("__CPU__", str(hints.get("cpu", "")))
                .replace("__SCL_FILES__", scl_files))
